version: "2.4"

services:
  xGenerator:
    image: ${REGISTRY}community/modules/custom-xgenerator-assets:${SITECORE_VERSION}-${NANOSERVER_VERSION}
    isolation: ${ISOLATION}
    build:
      context: .
      dockerfile: .\docker\Dockerfile
      args:
        BUILD_IMAGE: mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-${WINDOWSSERVERCORE_VERSION}
        BASE_IMAGE:  mcr.microsoft.com/windows/nanoserver:${NANOSERVER_VERSION}
        INTERNAL_NUGET_SOURCE: ${INTERNAL_NUGET_SOURCE}
        INTERNAL_NUGET_SOURCE_USERNAME: ${INTERNAL_NUGET_SOURCE_USERNAME}
        INTERNAL_NUGET_SOURCE_PASSWORD: ${INTERNAL_NUGET_SOURCE_PASSWORD}
